ActuatorNeededCoeffs = {"a": ["EncMountingDir",
                              "EncoderIndexOffset",
                              "JointKinematicDir",
                              "JointSensors_MotorPosition",
                              "JointSensors_OutputPosition",
                              "JointSensors_OutputVelocity",
                              "JointSensors_OutputForce",
                              "PositionOffset_Rad"],
                        "b": ["EncMountingDir",
                              "EncoderIndexOffset",
                              "JointKinematicDir",
                              "JointSensors_MotorPosition",
                              "JointSensors_OutputPosition",
                              "JointSensors_OutputVelocity",
                              "JointSensors_OutputForce",
                              "PositionOffset_Rad"],
                        "c": ["EncMountingDir",
                              "EncoderIndexOffset",
                              "JointKinematicDir",
                              "JointSensors_MotorPosition",
                              "JointSensors_OutputPosition",
                              "JointSensors_OutputVelocity",
                              "JointSensors_OutputForce",
                              "PositionOffset_Rad"],
                        "d": ["EncMountingDir",
                              "EncoderIndexOffset",
                              "JointKinematicDir",
                              "JointSensors_MotorPosition",
                              "JointSensors_OutputPosition",
                              "JointSensors_OutputVelocity",
                              "JointSensors_OutputForce",
                              "PositionOffset_Rad"],
                        "e": ["EncMountingDir",
                              "EncoderIndexOffset",
                              "JointKinematicDir",
                              "JointSensors_MotorPosition",
                              "JointSensors_OutputPosition",
                              "JointSensors_OutputVelocity",
                              "JointSensors_OutputForce",
                              "PositionOffset_Rad"],
                        "f": ["EncMountingDir",
                              "EncoderIndexOffset",
                              "JointKinematicDir",
                              "JointSensors_MotorPosition",
                              "JointSensors_OutputPosition",
                              "JointSensors_OutputVelocity",
                              "JointSensors_OutputForce",
                              "PositionOffset_Rad"],
                        "g": ["EncMountingDir",
                              "EncoderIndexOffset",
                              "JointKinematicDir",
                              "JointSensors_MotorPosition",
                              "JointSensors_OutputPosition",
                              "JointSensors_OutputVelocity",
                              "JointSensors_OutputForce",
                              "PositionOffset_Rad"],
                        "h_athena1": ["Pitch_offset",
                                      "Yaw_offset",
                                      "Pitch_hilmt",
                                      "Pitch_lolmt",
                                      "Pitch_cnvtrad",
                                      "Yaw_hilmt",
                                      "Yaw_lolmt",
                                      "Yaw_cnvtrad",
                                      "thumb_hicmdlmt",
                                      "thumb_locmdlmt",
                                      "thumb_posKP",
                                      "thumb_posKD",
                                      "thumb_dutylmt",
                                      "WL_Torq_KP",
                                      "WL_Torq_KD",
                                      "WL_hiposcmdlmt",
                                      "WL_loposcmdlmt",
                                      "WL_hivelcmdlmt",
                                      "WL_lovelcmdlmt",
                                      "WL_posKP",
                                      "WL_posKD",
                                      "WL_dutylmt",
                                      "Fing3_elecoffset",
                                      "Fing3_locmdlmt",
                                      "Fing3_hicmdlmt",
                                      "Fing3_posKP",
                                      "Fing3_posKD",
                                      "Fing3_dutylmt",
                                      "Fing3_APSoffset",
                                      "WR_Torq_KP",
                                      "WR_Torq_KD",
                                      "WR_hiposcmdlmt",
                                      "WR_loposcmdlmt",
                                      "WR_hivelcmdlmt",
                                      "WR_lovelcmdlmt",
                                      "WR_posKP",
                                      "WR_posKD",
                                      "WR_dutylmt"],
                        "h_athena2": ["Fing1_elecoffset",
                                      "Fing1_locmdlmt",
                                      "Fing1_hicmdlmt",
                                      "Fing1_posKP",
                                      "Fing1_posKD",
                                      "Fing1_dutylmt",
                                      "Fing1_APSoffset",
                                      "Fing2_elecoffset",
                                      "Fing2_locmdlmt",
                                      "Fing2_hicmdlmt",
                                      "Fing2_posKP",
                                      "Fing2_posKD",
                                      "Fing2_dutylmt",
                                      "Fing2_APSoffset",
                                      "Fing3_elecoffset",
                                      "Fing3_locmdlmt",
                                      "Fing3_hicmdlmt",
                                      "Fing3_posKP",
                                      "Fing3_posKD",
                                      "Fing3_dutylmt",
                                      "Fing3_APSoffset",
                                      "Fing4_elecoffset",
                                      "Fing4_locmdlmt",
                                      "Fing4_hicmdlmt",
                                      "Fing4_posKP",
                                      "Fing4_posKD",
                                      "Fing4_dutylmt",
                                      "Fing4_APSoffset"]
                        }


ClassNeededCoeffs = {"a": ["CurrentSafeLimit",
                           "EncoderCPR",
                           "FluxLinkage",
                           "Inductance_DAxis",
                           "Inductance_QAxis",
                           "JointMaxValue",
                           "JointMinValue",
                           "MotorWindingType",
                           "NumberOfPoles",
                           "WindingResistance"],
                     "b": ["CurrentSafeLimit",
                           "EncoderCPR",
                           "FluxLinkage",
                           "Inductance_DAxis",
                           "Inductance_QAxis",
                           "JointMaxValue",
                           "JointMinValue",
                           "MotorWindingType",
                           "NumberOfPoles",
                           "WindingResistance"],
                     "c": ["CurrentSafeLimit",
                           "EncoderCPR",
                           "FluxLinkage",
                           "Inductance_DAxis",
                           "Inductance_QAxis",
                           "JointMaxValue",
                           "JointMinValue",
                           "MotorWindingType",
                           "NumberOfPoles",
                           "WindingResistance"],
                     "d": ["CurrentSafeLimit",
                           "EncoderCPR",
                           "FluxLinkage",
                           "Inductance_DAxis",
                           "Inductance_QAxis",
                           "JointMaxValue",
                           "JointMinValue",
                           "MotorWindingType",
                           "NumberOfPoles",
                           "WindingResistance"],
                     "e": ["CurrentSafeLimit",
                           "EncoderCPR",
                           "FluxLinkage",
                           "Inductance_DAxis",
                           "Inductance_QAxis",
                           "JointMaxValue",
                           "JointMinValue",
                           "MotorWindingType",
                           "NumberOfPoles",
                           "WindingResistance"],
                     "f": ["CurrentSafeLimit",
                           "EncoderCPR",
                           "FluxLinkage",
                           "Inductance_DAxis",
                           "Inductance_QAxis",
                           "JointMaxValue",
                           "JointMinValue",
                           "MotorWindingType",
                           "NumberOfPoles",
                           "WindingResistance"],
                     "g": ["CurrentSafeLimit",
                           "EncoderCPR",
                           "FluxLinkage",
                           "Inductance_DAxis",
                           "Inductance_QAxis",
                           "JointMaxValue",
                           "JointMinValue",
                           "MotorWindingType",
                           "NumberOfPoles",
                           "WindingResistance"]
                     }

AllowedLocationFiles = {"a": ["shoulder_pitch.xml",
                              "hip_yaw_right.xml",
                              "hip_yaw_left.xml"],
                        "b": ["hip_roll_right.xml",
                              "hip_roll_left.xml",
                              "shoulder_roll_left.xml",
                              "shoulder_roll_right.xml"],
                        "c": ["hip_pitch.xml"],
                        "d": ["knee_pitch.xml"],
                        "e": ["trunk_linear.xml",
                              "ankle_linear.xml"],
                        "f": ["shoulder_yaw.xml",
                              "elbow_pitch_left.xml",
                              "elbow_pitch_right.xml"],
                        "g": ["neck_lower.xml",
                              "neck_upper.xml",
                              "neck_yaw.xml"]
                        }

AllowedClassFiles = {"a": "a.xml",
                     "b": "b.xml",
                     "c": "c.xml",
                     "d": "d.xml",
                     "e": "e.xml",
                     "f": "f.xml",
                     "g": "g.xml",
                     "h_athena1": None,
                     "h_athena2": None
                     }

AllowedSensorFiles = {"a": "sensors.xml",
                      "b": "sensors.xml",
                      "c": "sensors.xml",
                      "d": "sensors.xml",
                      "e": "sensors.xml",
                      "f": "sensors.xml",
                      "g": "sensors_leonidas.xml"}

ControllerNeededCoeffs = ["Commutation_Select"]

LocationNeededCoeffs = []

ModesNeededCoeffs = []

SafetyNeededCoeffs = ["CommTimeouts",
                      "TemperatureSensor_MaxTemp1",
                      "TemperatureSensor_MaxTemp2",
                      "TemperatureSensor_SensorLoc1",
                      "TemperatureSensor_SensorLoc2"]

SensorNeededCoeffs = ["BusVoltage_BitOffset",
                      "BusVoltage_SensorGain",
                      "IGainAmpsPerBit",
                      "PhaseACurOffset",
                      "PhaseBCurOffset",
                      "PhaseCCurOffset",
                      "Position_Alpha",
                      "Velocity_Alpha"]
